import { httpsCallable } from 'firebase/functions';
import { functions } from '@/libs/redux/store';

/**
 * Verifies the reCAPTCHA token using Firebase Callable Function.
 *
 * @param {string} captchaToken - The token generated by the reCAPTCHA component.
 * @param {number} [threshold=0.7] - The minimum score required to pass.
 * @returns {Promise<{ success: boolean, score: number, message?: string }>} - The verification result.
 * @throws {Error} If the token is missing or the verification fails.
 */
export async function verifyCaptcha(captchaToken, threshold = 0.7) {
  if (!captchaToken) {
    throw new Error('Please complete reCAPTCHA.');
  }
  try {
    const verifyRecaptcha = httpsCallable(functions, 'recaptchaVerifier'); 
    const response = await verifyRecaptcha({ captchaToken });
    const { success, score, message } = response.data; 

    console.log('reCAPTCHA verification result:', { success, score, message });

    if (!success || score < threshold) {
      throw new Error(message || 'Suspicious activity detected. Please try again.');
    }

    return { success, score, message };
  } catch (error) {
    throw new Error(error.message || 'An error occurred during reCAPTCHA verification.');
  }
}
