/**
 * Verifies the reCAPTCHA token by sending it to the server-side verification function.
 *
 * @param {string} captchaToken - The token generated by the reCAPTCHA component.
 * @param {string} apiUrl - The endpoint URL for reCAPTCHA verification.
 * @param {number} [threshold=0.7] - The minimum score required to pass.
 * @returns {Promise<{ success: boolean, score: number, message?: string }>} - The verification result.
 * @throws {Error} If the token is missing or the verification fails.
 */
export async function verifyCaptcha(captchaToken, apiUrl, threshold = 0.7) {
    if (!captchaToken) {
      throw new Error('Please complete reCAPTCHA.');
    }
  
    try {
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ captchaToken }),
      });
  
      const { success, score, message } = await response.json();
      console.log('reCAPTCHA verification result:', { success, score, message });
      if (!success || score < threshold) {
        throw new Error(message || 'Suspicious activity detected. Please try again.');
      }
  
      return { success, score, message };
    } catch (error) {
      throw new Error(error.message || 'An error occurred during reCAPTCHA verification.');
    }
}
  